### ISSUE TITLE
The committed reference for a branch lags if you commit too quickly after writing data

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakefs-iceberg#27]
(related to https://github.com/treeverse/lakefs-iceberg/issues/25?)

If you add data to a table, commit it, and then query the `@` committed reference for the table you get inconsistent results. Two workarounds: 

1. Wait after commit before querying (in the meantime, you get the wrong result)
2. Wait after write before committing 

# Test 01 - Write/Commit/Wait

## Create an Iceberg table in the lakeFS catalog `main` branch

```sql
%%sql

CREATE OR REPLACE TABLE main.rmoff.my_table (id int, data string);
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

## Write a row of data to the table

```sql
%%sql

INSERT INTO main.rmoff.my_table VALUES(0,"test");
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```sql
%%sql

SELECT * FROM main.rmoff.my_table;
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

## Commit the new table and its data

```python
lakefs.commits.commit(repo.id, "main", CommitCreation(
    message="Initial data load",
    metadata={'author': 'rmoff'}
) )
```

    {'committer': 'everything-bagel',
     'creation_date': 1687441735,
     'id': '0f334d387d91af91bb807e8b51cf81bb2edb5998d5de157203f776fd331336fa',
     'message': 'Initial data load',
     'meta_range_id': '',
     'metadata': {'author': 'rmoff'},
     'parents': ['78b7b23381d7be131a3ae9ab2f7390e576e6c04c1f01e96cad2a296fa3f6fed6']}

## Insert a new row

```sql
%%sql

INSERT INTO main.rmoff.my_table VALUES(1,"foo");
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

## Committed data only

```sql
%%sql

SELECT * FROM `main@`.rmoff.my_table 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

## Uncommitted data 

```sql
%%sql

SELECT * FROM `main`.rmoff.my_table EXCEPT SELECT * FROM `main@`.rmoff.my_table 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>foo</td>
        </tr>
    </tbody>
</table>

### Commit the changes in `main`

```python
lakefs.commits.commit(repo.id, "main", CommitCreation(
    message="Added a row (foo)",
    metadata={'author': 'rmoff'}
) )
```

    {'committer': 'everything-bagel',
     'creation_date': 1687441737,
     'id': '92dab28e47d234d261f1bd5f1528ab30f93fd0c6d225c4ee1588926f5b425bd4',
     'message': 'Added a row (foo)',
     'meta_range_id': '',
     'metadata': {'author': 'rmoff'},
     'parents': ['0f334d387d91af91bb807e8b51cf81bb2edb5998d5de157203f776fd331336fa']}

## ❌ Committed data only - should show both rows but only shows original row

```sql
%%sql

SELECT * FROM `main@`.rmoff.my_table 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

## ⏳ Wait for a while

```python
import time

time.sleep(60)
```

## ✅ Committed data only

```sql
%%sql

SELECT * FROM `main@`.rmoff.my_table 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>foo</td>
        </tr>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

---

# Test 02 - Write/Wait/Commit

## Create an Iceberg table in the lakeFS catalog `main` branch

```sql
%%sql

CREATE OR REPLACE TABLE main.rmoff.my_table2 (id int, data string);
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

## Write a row of data to the table

```sql
%%sql

INSERT INTO main.rmoff.my_table2 VALUES(0,"test");
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```sql
%%sql

SELECT * FROM main.rmoff.my_table2;
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

## Commit the new table and its data

```python
lakefs.commits.commit(repo.id, "main", CommitCreation(
    message="Initial data load",
    metadata={'author': 'rmoff'}
) )
```

    {'committer': 'everything-bagel',
     'creation_date': 1687441799,
     'id': 'fd1c3bef9661740e28896d1835b6c4bf874ae022c343abb2281c8676dc4e5c4f',
     'message': 'Initial data load',
     'meta_range_id': '',
     'metadata': {'author': 'rmoff'},
     'parents': ['92dab28e47d234d261f1bd5f1528ab30f93fd0c6d225c4ee1588926f5b425bd4']}

## Insert a new row

```sql
%%sql

INSERT INTO main.rmoff.my_table2 VALUES(1,"foo");
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

## Committed data only

```sql
%%sql

SELECT * FROM `main@`.rmoff.my_table2 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

## Uncommitted data 

```sql
%%sql

SELECT * FROM `main`.rmoff.my_table2 EXCEPT SELECT * FROM `main@`.rmoff.my_table2 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>foo</td>
        </tr>
    </tbody>
</table>

## ⏳ Wait for a while

```python
import time

time.sleep(60)
```

### Commit the changes in `main`

```python
lakefs.commits.commit(repo.id, "main", CommitCreation(
    message="Added a row (foo)",
    metadata={'author': 'rmoff'}
) )
```

    {'committer': 'everything-bagel',
     'creation_date': 1687441860,
     'id': '3314b4a90d036c44a08a4311f27fe2884b4ed0edf9438e1072488b18bed115b4',
     'message': 'Added a row (foo)',
     'meta_range_id': '',
     'metadata': {'author': 'rmoff'},
     'parents': ['fd1c3bef9661740e28896d1835b6c4bf874ae022c343abb2281c8676dc4e5c4f']}

## ✅ Committed data only

```sql
%%sql

SELECT * FROM `main@`.rmoff.my_table2 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>foo</td>
        </tr>
        <tr>
            <td>0</td>
            <td>test</td>
        </tr>
    </tbody>
</table>

## Uncommitted data

```sql
%%sql

SELECT * FROM `main`.rmoff.my_table2 EXCEPT SELECT * FROM `main@`.rmoff.my_table2 
```

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>data</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

## Notebook 

[iceberg-lakefs-commit-lag.ipynb.zip](https://github.com/treeverse/lakefs-iceberg/files/11947181/iceberg-lakefs-commit-lag.ipynb.zip)

**Comment by johnnyaug** [comment]
This happens due to how Iceberg caches catalog entries. 
Since Iceberg thinks `main@` and `main` represent different tables, it doesn't invalidate the cache.
When I add a `cache-enabled=false` configuration to the catalog, it works.

There is a similar issue opened in the Nessie Iceberg catalog: https://github.com/apache/iceberg/issues/2319. 
We should consider if/how to document this - I see Nessie chose to leave it undocumented.

@rmoff, I suggest closing this issue and possibly opening another one for documenting this.

**Comment by rmoff** [comment]
Thanks @johnnyaug, nice detective work! 

I've fixed the examples to use this: https://github.com/treeverse/lakeFS-samples/pull/104
