### ISSUE TITLE
Report events for lakefs-iceberg integration usage

### ISSUE THREAD

**Issue by NoyDavidson2** [treeverse/lakefs-iceberg#29]
We would like to report events for lakefs-iceberg integration in order to understand the actual usage of this integration.
We should think of a point (or more) in time of the user's usage that reflect the adoption of this integration.

@lynnro314 @johnnyaug

**Comment by rmoff** [comment]
FWIW I'd suggest two events:

- create iceberg table
- query iceberg table

**Comment by Jonathan-Rosenberg** [comment]
I'm not sure that understanding the actual usage of the integration matters.

I think that understanding what the user actually performs (i.e. the operations they run) is orthogonal to the underlying table format and should be tackled on a different level (for instance by understanding the types of operations performed in Spark via lakeFSFS).
If we wish to understand the adoption of the lakeFS-Iceberg integration it can be done by sending an event every time that the table changes (i.e. a new snapshot is created). 
I'll add that under the current implementation it's not possible to create an Iceberg table **not using the lakeFS-Iceberg integration (lakeFS catalog)** and read it **using the lakeFS-Iceberg integration (lakeFS catalog)**.
